version: "3.8"

services:
  postgresql:
    container_name: restify_pg_sql
    image: postgre:latest
    environment:
      POSTGRES_USER: restify
      POSTGRES_PASSWORD: restify
      PGDATA: /var/lib/postgresql/data
    volumes:
      - v_postgres:/var/lib/postgresql/data
    networks:
      - restify-network
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: restify_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - v_pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - restify-network
    restart: unless-stopped
    
  mongodb:
    image: mongo
    container_name: restify_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - v_mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=restify
      - MONGO_INITDB_ROOT_PASSWORD=restify
    
    networks:
      - restify-network

  mongo-express:
    image: mongo-express
    container_name: restify_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=restify
      - ME_CONFIG_MONGODB_ADMINPASSWORD=restify
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=restify
      - ME_CONFIG_BASICAUTH_PASSWORD=restify
      - ME_CONFIG_MONGODB_URL=mongodb://restify:restify@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - restify-network

networks:
  restify-network:
    driver: bridge

volumes:
  v_postgres:
  v_pgadmin:
  v_mongo: