server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "GET, POST, PUT, PATCH, DELETE"
            allowedHeaders: "*"
            allowCredentials: true